development:
  adapter: postgresql
  encoding: utf8
  database: matiybea_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: matiybea_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: d9o36i40dd263v
  pool: 5
  username: nctqsexglzjcnn
  password: OcWpPxmFBW-Q2Box3siSSDVPpU
